version: "3.8"

services:
  php_fpm:
      build: .
      container_name: coach_php_fpm
      restart: always
      volumes:
          - ./:/usr/share/nginx/coach
          - ./docker/php/8.2/cli/php.ini:/usr/local/etc/php/php.ini
      working_dir: /usr/share/nginx/coach
  nginx:
      image: nginx:1.20
      container_name: coach_nginx
      ports:
          - "443:443"
      restart: always
      volumes:
          - ./:/usr/share/nginx/coach
          - ./docker/nginx/conf.d/prod.conf:/etc/nginx/conf.d/prod.conf
          - ./docker/nginx/ssl/chesscoach.me.crt:/etc/nginx/ssl/chesscoach.me.crt
          - ./docker/nginx/ssl/chesscoach.me.key:/etc/nginx/ssl/chesscoach.me.key
      working_dir: /usr/share/nginx/coach
